version: "3.8"

services:
  instance:
    build: .
    command: bin/instance console
    ports:
      - "8090:8090"
    volumes:
      - ./var/filestorage:/plone/instance/var/filestorage
      - ./var/blobstorage:/plone/instance/var/blobstorage
      - ./src:/plone/instance/src

networks:
  plone:
