version: "3.8"

services:
  zeoserver:
    build: .
    command: bin/zeoserver fg
    volumes:
      - ./var/filestorage:/plone/instance/var/filestorage
      - ./var/blobstorage:/plone/instance/var/blobstorage
    networks:
      - plone

  instance:
    build: .
    command: bin/instance console
    ports:
      - "8080:8080"
    volumes:
      - ./src:/plone/instance/src
    depends_on:
      - zeoserver
    networks:
      - plone

networks:
  plone:
